Feat/create-row-between-component
IbraDajani/pokedex pull request #11
Opened 2022-07-11 09:50 UTC by Leeosteves

# 🚨 Fill in the fields below

[Create Row Between component](https://trello.com/c/D7z1NfRr/2-create-row-between-component)

## Description

```
~> Added Row between component to help us with the layout of the application
```

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Check list

- [ ] PRODUCT

  - [ ] Put PR link on ticket
  - [ ] Move the ticket

- [ ] DEVELOPERS

  - [ ] My code follows the style guidelines of this project
 - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings and I added `TODO:`, `FIXME:`

- [ ] REVIEW
  - [ ] Add reviewers: The entire team and most influential people in the area/project
  - [ ] Assign myself to it

🚨 - `Approve: Wait at least one influential in the project or more experienced`

2022-07-11 12:35 UTC, IbraDajani requested changes

2022-07-11 12:35 UTC, IbraDajani commented on src/App.tsx
> +import Between from './components/Row Between';
```suggestion
import RowBetween from './components/RowBetween';
```
We shouldn't have any component with space on the name

2022-07-11 12:35 UTC, IbraDajani commented on src/components/Row Between/styles.ts
> +`;
we're missing the `width: 100%`

2022-07-11 12:37 UTC, IbraDajani commented on src/App.tsx
> +import Between from './components/Row Between';
the component name is `RowBetween`

2022-07-11 19:03 UTC, IagoWag requested changes

2022-07-11 19:03 UTC, IagoWag commented on src/App.tsx
> +import Between from './components/Row Between';
correct name for the import is `Rowbetween`

2022-07-11 22:12 UTC, IagoWag approved these changes

2022-07-12 05:40 UTC, IbraDajani approved these changes

2022-07-12 05:45 UTC, merged