icon component implementation done
IbraDajani/pokedex pull request #12
Opened 2022-07-11 21:23 UTC by IagoWag

# 🚨 Fill in the fields below

[Create Icon component](https://trello.com/c/uOdquRWY/9-create-icon-component)

## Description

```
~> Icon component implementation
```

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] This is an example checked

- [ ] PRODUCT

  - [ ] Put PR link on ticket
  - [ ] Move the ticket

- [ ] DEVELOPERS

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code

- [ ] REVIEW
  - [ ] Add reviewers: The entire team and most influential people in the area/project
  - [ ] Assignees myself to it

🚨 - `Approve: Wait at least one influential in the project or more experienced`

# FRONTEND

## Design

## Screenshot or video of your application

🚨 - `Fill with your application`
<img  src="https://cdn.discordapp.com/attachments/848030065862377486/996164581422542988/Screenshot_1657574307.png" 
width="300px"
/>

2022-07-11 21:26 UTC, JeanSilvany requested changes

2022-07-11 21:26 UTC, JeanSilvany commented on src/App.tsx
>  };
O arquivo App.tsx está dando conflito pra mergear, será necessário corrigir!

2022-07-12 05:31 UTC, IbraDajani approved these changes

2022-07-12 05:31 UTC, IbraDajani commented on src/App.tsx
> +// import { Container } from './styles';
Remove imports you are not using

2022-07-12 05:41 UTC, IbraDajani approved these changes

2022-07-12 05:42 UTC, merged