Feat/create loading component
IbraDajani/pokedex pull request #25
Opened 2022-07-15 00:46 UTC by IagoWag

# 🚨 Fill in the fields below

[create Loading Component](https://trello.com/c/vNDEm7uJ/29-create-loading-component)

## Description

```
~> added loading component
```

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] This is an example checked

- [ ] PRODUCT

  - [ ] Put PR link on ticket
  - [ ] Move the ticket

- [ ] DEVELOPERS

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
 

- [ ] REVIEW
  - [ ] Add reviewers: The entire team and most influential people in the area/project
  - [ ] Assignees myself to it

🚨 - `Approve: Wait at least one influential in the project or more experienced`

# FRONTEND

## Design

## Screenshot or video of your application

🚨 - `Fill with your application`

https://user-images.githubusercontent.com/102339646/179124474-d65d7ddc-9a69-4e7a-8d10-7cf47b6b6ae1.mp4

2022-07-15 09:04 UTC, IbraDajani requested changes
Pay attention to the branches you are using and what you are pushing... there is nothing remotely related to Loading component in these commits

2022-07-15 16:14 UTC, JeanSilvany commented
Mas cadê o componente de Loader nos arquivos?

2022-07-16 00:24 UTC, IbraDajani approved these changes

2022-07-16 00:25 UTC, IbraDajani approved these changes

2022-07-16 00:28 UTC, merged