Feat/responsive design home
IbraDajani/pokedex pull request #43
Opened 2022-07-19 11:05 UTC by Leeosteves

# 🚨 Fill in the fields below

[Refactor HomeScreen to a more responsive design](https://trello.com/c/4Dq6vQ8i/38-refactor-homescreen-to-a-more-responsive-design)

## Description

```
~>Added responsiveness on home screen.
~>Added global header component.
~>New background for testing cards.
~>Image of the logo readjusted.
```

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

- [ ] PRODUCT

  - [ ] Put PR link on ticket
  - [ ] Move the ticket

- [ ] DEVELOPERS

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings and I added `TODO:`, `FIXME:`

- [ ] REVIEW
  - [ ] Add reviewers: The entire team and most influential people in the area/project
  - [ ] Assignees myself to it

🚨 - `Approve: Wait at least one influential in the project or more experienced`

# FRONTEND

## Screenshot or video of your application

🚨 - `Fill with your application`

https://user-images.githubusercontent.com/106574167/179735734-5034e458-2d4b-4df9-a968-84bd4789b03a.mp4

https://user-images.githubusercontent.com/106574167/179735745-55112a8a-80e2-4fa0-b942-f1cb7e3aa281.mp4

2022-07-19 13:26 UTC, IbraDajani requested changes

2022-07-19 13:26 UTC, IbraDajani commented on src/components/ButtonHeader/index.tsx
> +    </ButtonPress>
Change the name of the Component to Container

to follow the styleguides

2022-07-19 13:26 UTC, IbraDajani commented on src/components/ButtonHeader/styles.ts
> +export const ButtonPress = styled.TouchableOpacity``;
Here too

2022-07-19 13:26 UTC, IbraDajani commented on src/components/Header/styles.ts
> +  flex-direction: row-reverse;
No need to have it reversed... use only row

2022-07-19 13:26 UTC, IbraDajani commented on src/components/Header/types.ts
> +  children?: string | React.ReactNode;
Why string?

2022-07-19 13:26 UTC, IbraDajani commented on src/screens/Home/index.tsx
> +          onPress={() => navigate('Internal')}
Create a separate function to handle the navigate and pass it on this onPress

2022-07-20 03:58 UTC, Leeosteves commented on src/components/ButtonHeader/index.tsx
> +    </ButtonPress>
resolved in commit 48f20a7003b832e3fc2d81185ddd2925d3b8c45f

2022-07-20 03:58 UTC, Leeosteves commented on src/components/ButtonHeader/styles.ts
> +export const ButtonPress = styled.TouchableOpacity``;
resolved in commit 48f20a7003b832e3fc2d81185ddd2925d3b8c45f

2022-07-20 03:58 UTC, Leeosteves commented on src/components/Header/types.ts
> +  children?: string | React.ReactNode;
resolved in commit 48f20a7003b832e3fc2d81185ddd2925d3b8c45f

2022-07-20 03:58 UTC, Leeosteves commented on src/screens/Home/index.tsx
> +          onPress={() => navigate('Internal')}
resolved in commit 48f20a7003b832e3fc2d81185ddd2925d3b8c45f

2022-07-20 04:01 UTC, Leeosteves commented on src/components/Header/styles.ts
> +  flex-direction: row-reverse;
there is no way to change why I want the icons to start from right to left, otherwise the row or align items flex end will not work.

2022-07-20 12:51 UTC, IbraDajani requested changes
Switch back the pokeball image inside the Pokemon card

2022-07-20 12:51 UTC, IbraDajani commented on src/screens/Home/index.tsx
> +  const handlerNavigateInternal = () => {
```suggestion
  const handleNavigateToInternal = () => {
```

Change to something like this

2022-07-20 12:51 UTC, IbraDajani commented on src/screens/Home/index.tsx
> +    return navigate('Internal');
and remove the return... there is no need to return

2022-07-20 15:42 UTC, Leeosteves commented on src/screens/Home/index.tsx
> +  const handlerNavigateInternal = () => {
resolved in commit 976fa0aa6c578fbf09030956cfa3018741ea05c8

2022-07-20 15:42 UTC, Leeosteves commented on src/screens/Home/index.tsx
> +    return navigate('Internal');
resolved in commit 976fa0aa6c578fbf09030956cfa3018741ea05c8

2022-07-20 16:13 UTC, IbraDajani approved these changes

2022-07-20 16:14 UTC, IbraDajani approved these changes

2022-07-20 16:40 UTC, merged