Feat/drawer navigator
IbraDajani/pokedex pull request #48
Opened 2022-07-24 22:02 UTC by Leeosteves

# 🚨 Fill in the fields below

[Add Drawer Navigation](https://trello.com/c/hkFabkmN/43-add-drawer-navigation)

## Description

```
~>Added navigation drawer with functions to switch screens.
~>Added avatar component
~>Added logout button in drawer along with favorites screen
```

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

- [ ] PRODUCT

  - [ ] Put PR link on ticket
  - [ ] Move the ticket

- [ ] DEVELOPERS

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings and I added `TODO:`, `FIXME:`

- [ ] REVIEW
  - [ ] Add reviewers: The entire team and most influential people in the area/project
  - [ ] Assignees myself to it

🚨 - `Approve: Wait at least one influential in the project or more experienced`

# FRONTEND

## Screenshot or video of your application

🚨 - `Fill with your application`

https://user-images.githubusercontent.com/106574167/180667562-0fd9f73e-547b-43a3-ac62-e8ea7831310d.mp4

2022-07-25 00:27 UTC, IbraDajani requested changes

2022-07-25 00:27 UTC, IbraDajani commented on src/screens/Drawer/DrawerContent.tsx
> +        </TouchableOpacity> */}
```suggestion
      
```

Remove comments

2022-07-25 00:27 UTC, IbraDajani commented on src/screens/Drawer/DrawerContent.tsx
> +          onPress={() => navigate('Home')}
Create a functions to deal with this navigation and then pass it on this onPress

2022-07-25 00:27 UTC, IbraDajani commented on src/screens/Drawer/DrawerContent.tsx
> +          onPress={() => {}}
Remove anonymous functions

2022-07-25 00:27 UTC, IbraDajani commented on src/screens/Drawer/DrawerContent.tsx
> +          icon="darkmode"
remove ir

2022-07-25 00:27 UTC, IbraDajani commented on src/screens/Drawer/localComponents/RouteNavigationButton/types.ts
> +export type RouteName = 'Home' | 'Favorites' | 'Dark Mode';
```suggestion
export type RouteName = 'Home' | 'Favorites' ;
```

2022-07-25 00:27 UTC, IbraDajani commented on src/screens/Drawer/localComponents/RouteNavigationButton/types.ts
> +export type RouteName = 'Home' | 'Favorites' | 'Dark Mode';
Remove the Dark type

2022-07-25 00:27 UTC, IbraDajani commented on src/screens/Drawer/styles.ts
> +  flex-direction: column;
the default flex direction on React native is column... there is no need to add it on the View

2022-07-25 00:27 UTC, IbraDajani commented on src/screens/Drawer/styles.ts
> +  /* border-radius: 24px; */
Remove comments

2022-07-25 00:27 UTC, IbraDajani commented on src/screens/Drawer/styles.ts
> +  /* padding-left: 15px; */
Remove comments

2022-07-25 00:27 UTC, IbraDajani commented on src/screens/Favorites/index.tsx
> +import pokeBallImage from '~/assets/images/pokeball.png';
Sort import order by its type

2022-07-25 00:27 UTC, IbraDajani commented on src/screens/Favorites/index.tsx
> +        <ButtonHeader icon="menu" onPress={() => navigation.toggleDrawer()} />
Create a function to handle this toggle and pass it on this onPress

2022-07-25 00:27 UTC, IbraDajani commented on src/screens/Favorites/index.tsx
> +        <ButtonHeader icon="closedEye" onPress={() => goBack()} />
here too

2022-07-25 00:27 UTC, IbraDajani commented on src/screens/Favorites/styles.ts
> +export const BackgroundImage = styled(Image)`
```suggestion
export const BackgroundImage = styled.Image`
```

THERE IS NO NEED TO IMPORT THE COMPONENT FROM THE REACT NATIVE IF YOU CAN JUST USE IT LIKE STYLED.COMPONENT

2022-07-25 00:27 UTC, IbraDajani commented on src/screens/Favorites/styles.ts
> +import {Image} from 'react-native';
remove it

2022-07-25 00:27 UTC, IbraDajani commented on src/screens/Home/styles.ts
> +import {Image} from 'react-native';
REMOVE IT

2022-07-25 00:27 UTC, IbraDajani commented on src/screens/Home/styles.ts
> +export const BackgroundImage = styled(Image)`
```suggestion
export const BackgroundImage = styled.Image`
```

2022-07-25 00:32 UTC, IbraDajani commented
REMOVE THE POKEBALL IMAGE FROM THE DRAWER NAVIGATOR... JUST LEAVE THE POKEBALL IMAGE FROM THE HOMESCREEN

2022-07-25 00:41 UTC, IbraDajani commented
And fix the drawer navigation type

2022-07-25 00:42 UTC, IbraDajani commented
And add the params type too

2022-07-25 00:46 UTC, IbraDajani commented
Create a ViewModel to every screen created in these commits

2022-07-25 02:41 UTC, Leeosteves commented on src/constants/icons.ts
> +import darkmode from '../assets/icons/darkmode/Vector.png';
resolved in commit 30a06e50e485c45aaf6a9e54390391fee0ddfd33

2022-07-25 02:41 UTC, Leeosteves commented on src/constants/icons.ts
> +  | 'darkmode'
resolved in commit 30a06e50e485c45aaf6a9e54390391fee0ddfd33

2022-07-25 02:41 UTC, Leeosteves commented on src/constants/icons.ts
> +  darkmode,
resolved in commit 30a06e50e485c45aaf6a9e54390391fee0ddfd33

2022-07-25 02:41 UTC, Leeosteves commented on src/navigation/DrawerNavigationRoutes/index.tsx
> +      }}>
resolved in commit 30a06e50e485c45aaf6a9e54390391fee0ddfd33

2022-07-25 02:41 UTC, Leeosteves commented on src/navigation/StackNavigatorRoutes/SignedInRoutes/index.tsx
> +import Internal from '../../../screens/Internal';
resolved in commit 30a06e50e485c45aaf6a9e54390391fee0ddfd33

2022-07-25 02:41 UTC, Leeosteves commented on src/screens/Drawer/DrawerContent.tsx
> +import {ActivityIndicator, View} from 'react-native';
resolved in commit 30a06e50e485c45aaf6a9e54390391fee0ddfd33

2022-07-25 02:41 UTC, Leeosteves commented on src/screens/Drawer/DrawerContent.tsx
> +import RouteNavigationButton from './localComponents/RouteNavigationButton';
resolved in commit 30a06e50e485c45aaf6a9e54390391fee0ddfd33

2022-07-25 02:42 UTC, Leeosteves commented on src/screens/Drawer/DrawerContent.tsx
> +        </TouchableOpacity> */}
resolved in commit 30a06e50e485c45aaf6a9e54390391fee0ddfd33

2022-07-25 02:42 UTC, Leeosteves commented on src/screens/Drawer/DrawerContent.tsx
> +          onPress={() => navigate('Home')}
resolved in commit 30a06e50e485c45aaf6a9e54390391fee0ddfd33

2022-07-25 02:42 UTC, Leeosteves commented on src/screens/Drawer/DrawerContent.tsx
> +  const [currentTab, setCurrentTab] = useState<RouteName>('Favorites');
resolved in commit 30a06e50e485c45aaf6a9e54390391fee0ddfd33

2022-07-25 02:42 UTC, Leeosteves commented on src/screens/Drawer/DrawerContent.tsx
> +          onPress={() => {}}
resolved in commit 30a06e50e485c45aaf6a9e54390391fee0ddfd33

2022-07-25 02:42 UTC, Leeosteves commented on src/screens/Drawer/DrawerContent.tsx
> +          icon="darkmode"
resolved in commit 30a06e50e485c45aaf6a9e54390391fee0ddfd33

2022-07-25 03:09 UTC, IbraDajani requested changes

2022-07-25 03:09 UTC, IbraDajani commented on src/screens/Favorites/useFavoritesController.ts
> +    navigation.dispatch(DrawerActions.toggleDrawer());
```suggestion
  dispatch(DrawerActions.toggleDrawer());
```

2022-07-25 03:09 UTC, IbraDajani commented on src/screens/Drawer/styles.ts
> +  /* position: absolute;
Remove comments

2022-07-25 03:09 UTC, IbraDajani commented on src/screens/Drawer/styles.ts
> +  right: 20px; */
Remove comments

2022-07-25 03:09 UTC, IbraDajani commented on src/screens/Favorites/index.tsx
> +  const {openDrawer} = useFavoritesController();
/**
* Hooks
/**

2022-07-25 03:09 UTC, IbraDajani commented on src/screens/Favorites/styles.ts
> +  left: 235px;
Change this to a right property with a more precise value

2022-07-25 03:09 UTC, IbraDajani commented on src/screens/Home/useHomeController.ts
> +  const navigation = useNavigation();
```suggestion
  const {dispatch} = useNavigation();
```

2022-07-25 03:09 UTC, IbraDajani commented on src/screens/Home/useHomeController.ts
> +    navigation.dispatch(DrawerActions.toggleDrawer());
```suggestion
    dispatch(DrawerActions.toggleDrawer());
```

2022-07-25 03:09 UTC, IbraDajani commented on src/screens/Drawer/DrawerContent.tsx
> +              style={{transform: [{rotate: spin}]}}
Move this inline styling somewhere else like a custom hook for the animation

2022-07-26 05:24 UTC, Leeosteves commented on src/navigation/DrawerNavigationRoutes/index.tsx
> +      drawerContent={() => <DrawerContent />}
resolved in commit 2c631c64d3008d3793416ddfe5451f0001937690

2022-07-26 05:24 UTC, Leeosteves commented on src/navigation/DrawerNavigationRoutes/index.tsx
> +        options={{swipeEnabled: false}}
resolved in commit 2c631c64d3008d3793416ddfe5451f0001937690

2022-07-26 05:24 UTC, Leeosteves commented on src/screens/Drawer/DrawerContent.tsx
> +              style={{transform: [{rotate: spin}]}}
resolved in commit 2c631c64d3008d3793416ddfe5451f0001937690

2022-07-26 05:24 UTC, Leeosteves commented on src/screens/Drawer/styles.ts
> +export const AvatarProfile = styled(Avatar)``;
resolved in commit 2c631c64d3008d3793416ddfe5451f0001937690

2022-07-26 05:24 UTC, Leeosteves commented on src/screens/Drawer/styles.ts
> +  flex-direction: column;
resolved in commit 2c631c64d3008d3793416ddfe5451f0001937690

2022-07-26 05:24 UTC, Leeosteves commented on src/screens/Drawer/styles.ts
> +`;
resolved in commit 2c631c64d3008d3793416ddfe5451f0001937690

2022-07-26 05:24 UTC, Leeosteves commented on src/screens/Drawer/styles.ts
> +  margin-bottom: 170px;
resolved in commit 2c631c64d3008d3793416ddfe5451f0001937690

2022-07-26 05:24 UTC, Leeosteves commented on src/screens/Drawer/useDrawerContentController.ts
> +  ).start();
resolved in commit 2c631c64d3008d3793416ddfe5451f0001937690

2022-07-26 05:24 UTC, Leeosteves commented on src/screens/Favorites/useFavoritesController.ts
> +  const navigation = useNavigation();
resolved in commit 2c631c64d3008d3793416ddfe5451f0001937690

2022-07-26 05:24 UTC, Leeosteves commented on src/screens/Favorites/useFavoritesController.ts
> +    navigation.dispatch(DrawerActions.toggleDrawer());
resolved in commit 2c631c64d3008d3793416ddfe5451f0001937690

2022-07-26 05:24 UTC, Leeosteves commented on src/screens/Favorites/index.tsx
> +  const {openDrawer} = useFavoritesController();
resolved in commit 2c631c64d3008d3793416ddfe5451f0001937690

2022-07-26 05:24 UTC, Leeosteves commented on src/screens/Favorites/styles.ts
> +  left: 235px;
resolved in commit 2c631c64d3008d3793416ddfe5451f0001937690

2022-07-26 05:24 UTC, Leeosteves commented on src/screens/Home/useHomeController.ts
> +  const navigation = useNavigation();
resolved in commit 2c631c64d3008d3793416ddfe5451f0001937690

2022-07-26 05:24 UTC, Leeosteves commented on src/screens/Home/useHomeController.ts
> +    navigation.dispatch(DrawerActions.toggleDrawer());
resolved in commit 2c631c64d3008d3793416ddfe5451f0001937690

2022-07-26 05:30 UTC, IbraDajani approved these changes
🔥

2022-07-26 05:38 UTC, IagoWag approved these changes

2022-07-26 05:38 UTC, merged