Feat/create internal screen
IbraDajani/pokedex pull request #49
Opened 2022-07-25 03:24 UTC by IagoWag

# 🚨 Fill in the fields below

[Add Ticket link](https://example.com)

## Description

```
~> created internal screen 
```

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Checklist

- [x] This is an example checked

- [ ] PRODUCT

  - [ ] Put PR link on ticket
  - [ ] Move the ticket

- [ ] DEVELOPERS

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] My changes generate no new warnings and I added `TODO:`, `FIXME:`

- [ ] REVIEW
  - [ ] Add reviewers: The entire team and most influential people in the area/project
  - [ ] Assignees myself to it

🚨 - `Approve: Wait at least one influential in the project or more experienced`

# FRONTEND

## Design

[Add link to design](https://example.com)

🚨 - `If your task has a design on figma, put a screenshot here`

![internal](https://user-images.githubusercontent.com/102339646/180692628-b300ed43-2a0d-4730-b994-4dd7be7c6162.png)

## Screenshot or video of your application

🚨 - `Fill with your application`

https://user-images.githubusercontent.com/102339646/180693088-bc1c23bc-c010-4891-a9e1-713f58707d27.mp4

2022-07-25 03:52 UTC, IbraDajani requested changes
Add the correct heart icon and implement it

2022-07-25 03:52 UTC, IbraDajani commented on src/screens/Internal/localComponents/BaseStats/index.tsx
> +        <Text color="#5c6a70">Total</Text>
if the style is the same, create a Styled Text component to use in this screen

2022-07-25 03:52 UTC, IbraDajani commented on src/screens/Internal/localComponents/BaseStats/styles.ts
> +export interface PropsStats {}
Remove if its not being used

2022-07-25 03:52 UTC, IbraDajani commented on src/screens/Internal/styles.ts
> +`;
isn't this the exactly same thing as our RowBetween component?

2022-07-25 03:52 UTC, IbraDajani commented on src/screens/Internal/styles.ts
> +`;
Remove it if you are not using

2022-07-25 03:52 UTC, IbraDajani commented on src/screens/Internal/styles.ts
> +export const OptionButton = styled.Pressable``;
Remove it if there is no Styles on it... just use a simple Pressable component on the screen

2022-07-27 01:54 UTC, Leeosteves approved these changes

2022-08-01 06:14 UTC, IbraDajani requested changes
Upload a video of the application on a smaller device please

2022-08-01 06:14 UTC, IbraDajani commented on src/screens/Internal/localComponents/BaseStats/index.tsx
> +                  progress={item.value / 100}
Create a function to handle this prop value calculation to make it more organized

2022-08-01 06:14 UTC, IbraDajani commented on src/screens/Internal/localComponents/BaseStats/types.ts
> +  item: PokemonDTO | undefined;
why undefined?

2022-08-01 06:14 UTC, IbraDajani commented on src/screens/Internal/localComponents/Evolutions/index.tsx
> +            item={apiJSON.find(e => e.name === item?.prev_evolution?.[i]?.name)}
maybe it would be nice to create a separate function to handle this find method and pass the function inside the param as it's value

2022-08-01 06:14 UTC, IbraDajani commented on src/screens/Internal/localComponents/Evolutions/index.tsx
> +            item={apiJSON.find(e => e.name === item?.next_evolution?.[i]?.name)}
here too

2022-08-01 06:14 UTC, IbraDajani commented on src/screens/Internal/localComponents/Evolutions/index.tsx
> +      )}
Create a component with some kind of image to be displayed when no evolutions exists for that specific pokemon

2022-08-01 06:14 UTC, IbraDajani commented on src/screens/Internal/localComponents/Evolutions/styles.ts
> +`;
maybe adding `align-items: center` to deal with the vertical alignment would be a good thing

2022-08-01 06:14 UTC, IbraDajani commented on src/screens/Internal/localComponents/Evolutions/types.ts
> +  item?: PokemonDTO;
here, the type is not undefined like the previous one

why is that?

2022-08-01 06:14 UTC, IbraDajani commented on src/screens/Internal/mocks.ts
> +];
change those ids to match the enum type

2022-08-01 06:14 UTC, IbraDajani commented on src/screens/Internal/styles.ts
> +export const Container = styled(SafeAreaView)<{BGColor?: string}>`
move that interface to a types.ts file inside the internal screen folder and import it back here

2022-08-01 06:14 UTC, IbraDajani commented on src/screens/Internal/styles.ts
> +`;
is this component really necessary?

2022-08-01 06:14 UTC, IbraDajani commented on src/screens/Internal/styles.ts
> +export const PokemonBackgroundImage = styled.Image`
if this is the background pokeball image, change the name of the component to something more precise

like: PokeballBackgroundImage

2022-08-01 06:14 UTC, IbraDajani commented on src/screens/Internal/styles.ts
> +export const DetailOptionButtonBackground = styled.View`
```suggestion
export const DetailOptionButtonBackgroundBar = styled.View`
```

mind the name

2022-08-01 06:18 UTC, IbraDajani commented
The Pokeball image should be moved a little more to the bottom to match the Design prototype

2022-08-05 23:18 UTC, IbraDajani requested changes

2022-08-05 23:18 UTC, IbraDajani commented on src/screens/Internal/index.tsx
> +          <Pressable onPress={() => setlikeOption(oldState => !oldState)}>
create a separated function to handle this onPress like:

`const handleLikeOptionStateChange = () => {
   setlikeOption(oldState => !oldState)
}`

and pass it to this onPress

2022-08-05 23:18 UTC, IbraDajani commented on src/screens/Internal/mocks.ts
> +];
That's nice

2022-08-05 23:18 UTC, IbraDajani commented on src/screens/Internal/styles.ts
> +  background-color: #ffffff60;
Here, that `60` on the final of the hash means 60% of opacity

6 lines later, you set the opacity to 80%

now, because of the 80% being on the bottom of the style object, the Component will have 80% of opacity.


you can add the background color to `#ffffff80` and remove the opacity 0.8 on the line 34
or remove this `60` of the final of the hash and keep the opacity 0.8 in the line 34

2022-08-05 23:18 UTC, IbraDajani commented on src/screens/Internal/types.ts
> +}
🔥

2022-08-05 23:18 UTC, IbraDajani commented on src/screens/Login/index.tsx
> +        'https://pisosipanema.com.br/wp-content/uploads/2021/11/bocos_6_furos_para_topo.png',
Grande homem 😭

2022-08-06 03:32 UTC, IagoWag commented on src/screens/Internal/styles.ts
> +`;
yes

2022-08-06 03:33 UTC, IagoWag commented on src/screens/Internal/styles.ts
> +`;
no

2022-08-06 03:34 UTC, IagoWag commented on src/screens/Login/index.tsx
> +        'https://pisosipanema.com.br/wp-content/uploads/2021/11/bocos_6_furos_para_topo.png',
kkkkkkk

2022-08-06 09:03 UTC, IagoWag commented on src/screens/Internal/localComponents/BaseStats/types.ts
> +  item: PokemonDTO | undefined;
already changed to item: PokemonDTO

2022-08-06 09:03 UTC, IagoWag commented on src/screens/Internal/localComponents/BaseStats/types.ts
> +  item: PokemonDTO | undefined;
removed undefined

2022-08-06 09:10 UTC, IbraDajani approved these changes

2022-08-06 09:10 UTC, merged