Feat/favorite screen
IbraDajani/pokedex pull request #52
Opened 2022-08-11 16:40 UTC by Leeosteves

# 🚨 Fill in the fields below

[Create Favorite Pokemons screen](https://trello.com/c/ELwriLg6/45-create-favorite-pokemons-screen)

## Description

```
~>Added favorite screen.
~>Added functions to add and remove pokemon from favorites list.
~>Added reactotron library.
```

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

- [ ] PRODUCT

  - [ ] Put PR link on ticket
  - [ ] Move the ticket

- [ ] DEVELOPERS

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings and I added `TODO:`, `FIXME:`

- [ ] REVIEW
  - [ ] Add reviewers: The entire team and most influential people in the area/project
  - [ ] Assignees myself to it

🚨 - `Approve: Wait at least one influential in the project or more experienced`

# FRONTEND

## Screenshot or video of your application

🚨 - `Fill with your application

https://user-images.githubusercontent.com/106574167/184186438-742127de-95f6-4558-874a-f4e3385880b7.mp4

2022-08-15 23:34 UTC, IbraDajani requested changes

2022-08-15 23:34 UTC, IbraDajani commented on src/@types/dtos/pokemonDTO.ts
> +  idFavorite?: number;
why there is a `?` on it

and why is there a idFavorite?

didn't we removed the logic that used this prop?

2022-08-15 23:34 UTC, IbraDajani commented on src/@types/images.d.ts
> +declare module '*.jpg';
are we still using the jpg file?

2022-08-15 23:34 UTC, IbraDajani commented on src/@types/images.d.ts
> +declare module 'react-native-linear-gradient';
remove this if the linear gradient is not being used anymore

2022-08-15 23:34 UTC, IbraDajani commented on src/App.tsx
> +import {Favorite} from './context/Favorite';
change the name of this context to something more specific

like

FavoriteProvider

just like the AuthProvider

2022-08-15 23:34 UTC, IbraDajani commented on src/components/Empty/index.tsx
> +      <Icon size={36} icon="empty" />
just increase the size of the component.... and there is no need to those Separators around the Icon

remove the Separators and adjust the position inside the screen that you are using the component

2022-08-15 23:34 UTC, IbraDajani commented on src/constants/icons.ts
> +import Water from '~/assets/icons/types/water/Vector.png';
we should have a @2x and a @3x for each one of those icons

2022-08-15 23:34 UTC, IbraDajani commented on src/context/Favorite/types.ts
> +  deleteSelectItems: () => void;
```suggestion
  deleteSelectedItems: () => void;
```

2022-08-15 23:34 UTC, IbraDajani commented on src/context/Favorite/types.ts
> +  getPokemonFavorite: (item: PokemonDTO) => void;
```suggestion
  getFavoritePokemon: (item: PokemonDTO) => void;
```

2022-08-15 23:34 UTC, IbraDajani commented on src/context/Favorite/types.ts
> +  selectItems: number[];
```suggestion
  selectedPokemons: number[];
```

2022-08-15 23:34 UTC, IbraDajani commented on src/hooks/useFavorite/index.tsx
> +export default useFavorites;
That's nice

2022-08-15 23:34 UTC, IbraDajani commented on src/screens/Favorites/index.tsx
> +        />
Nice

2022-08-15 23:34 UTC, IbraDajani commented on src/screens/Favorites/localComponents/PokemonCardFavorite/types.ts
> +};
why undefined?

2022-08-15 23:34 UTC, IbraDajani commented on src/screens/Favorites/localComponents/PokemonCardFavorite/types.ts
> +  style?: string;
what is this style?

2022-08-15 23:34 UTC, IbraDajani commented on src/screens/Favorites/localComponents/PokemonCardFavorite/usePokemonCardController.ts
> +  };
Separate this into 2 functions... 

its kinda shady do this way

there is 2 completely different thing happening for each case of this if else structure

2022-08-15 23:34 UTC, IbraDajani commented on src/screens/Favorites/styles.ts
> +export const Container = styled.SafeAreaView`
```suggestion
export const Container = styled(SafeAreaView)`
```

use the safe area view from the react-native-safe-area-context

2022-08-15 23:34 UTC, IbraDajani commented on src/screens/Favorites/styles.ts
> +export const Container = styled.SafeAreaView`
dont forget the import

2022-08-15 23:34 UTC, IbraDajani commented on src/screens/Favorites/styles.ts
> +  padding-bottom: 200px;
Find a way to remove this padding and still have the task fully functional

2022-08-15 23:34 UTC, IbraDajani commented on src/screens/Internal/index.tsx
> +              icon={ifExists(item) ? 'favorite' : 'like'}
create two memos to handle these props values

use the same logic on it

just to avoid too many ternary operations on the View

2022-08-15 23:34 UTC, IbraDajani commented on src/screens/Internal/localComponents/Evolutions/index.tsx
> +      {!item?.prev_evolution && !item?.next_evolution && <Empty />}
Nice

2022-08-15 23:34 UTC, IbraDajani commented on src/screens/Internal/useInternalControler.tsx
> +export const useInternalControler = item => {
maybe we need to type the item

2022-08-15 23:51 UTC, IbraDajani commented
and write a better report on the start of the PR

2022-08-16 06:15 UTC, Leeosteves commented on package.json
> +    "react-native-linear-gradient": "^2.6.2",
Resolved in commit 8be304bef5499c5ee9916c22687b4abda5363ca6

2022-08-16 06:15 UTC, Leeosteves commented on src/@types/dtos/pokemonDTO.ts
> +  idFavorite?: number;
Resolved in commit 8be304bef5499c5ee9916c22687b4abda5363ca6

2022-08-16 06:15 UTC, Leeosteves commented on src/@types/images.d.ts
> +declare module '*.jpg';
Resolved in commit 8be304bef5499c5ee9916c22687b4abda5363ca6

2022-08-16 06:16 UTC, Leeosteves commented on src/@types/images.d.ts
> +declare module 'react-native-linear-gradient';
Resolved in commit 8be304bef5499c5ee9916c22687b4abda5363ca6

2022-08-16 06:16 UTC, Leeosteves commented on src/App.tsx
> +import {Favorite} from './context/Favorite';
Resolved in commit 8be304bef5499c5ee9916c22687b4abda5363ca6

2022-08-16 06:16 UTC, Leeosteves commented on src/components/Empty/index.tsx
> +      <Icon size={36} icon="empty" />
Resolved in commit 8be304bef5499c5ee9916c22687b4abda5363ca6

2022-08-16 06:16 UTC, Leeosteves commented on src/constants/icons.ts
> +import Water from '~/assets/icons/types/water/Vector.png';
Resolved in commit 8be304bef5499c5ee9916c22687b4abda5363ca6

2022-08-16 06:16 UTC, Leeosteves commented on src/context/Favorite/types.ts
> +  getPokemonFavorite: (item: PokemonDTO) => void;
Resolved in commit 8be304bef5499c5ee9916c22687b4abda5363ca6

2022-08-16 06:16 UTC, Leeosteves commented on src/context/Favorite/types.ts
> +  deleteSelectItems: () => void;
Resolved in commit 8be304bef5499c5ee9916c22687b4abda5363ca6

2022-08-16 06:16 UTC, Leeosteves commented on src/context/Favorite/types.ts
> +  selectItems: number[];
Resolved in commit 8be304bef5499c5ee9916c22687b4abda5363ca6

2022-08-16 06:16 UTC, Leeosteves commented on src/screens/Favorites/localComponents/PokemonCardFavorite/types.ts
> +};
Resolved in commit 8be304bef5499c5ee9916c22687b4abda5363ca6

2022-08-16 06:16 UTC, Leeosteves commented on src/screens/Favorites/localComponents/PokemonCardFavorite/types.ts
> +  style?: string;
Resolved in commit 8be304bef5499c5ee9916c22687b4abda5363ca6

2022-08-16 06:16 UTC, Leeosteves commented on src/screens/Favorites/localComponents/PokemonCardFavorite/usePokemonCardController.ts
> +  };
Resolved in commit 8be304bef5499c5ee9916c22687b4abda5363ca6

2022-08-16 06:16 UTC, Leeosteves commented on src/screens/Favorites/styles.ts
> +export const Container = styled.SafeAreaView`
Resolved in commit 8be304bef5499c5ee9916c22687b4abda5363ca6

2022-08-16 06:17 UTC, Leeosteves commented on src/screens/Favorites/styles.ts
> +  padding-bottom: 200px;
Resolved in commit 8be304bef5499c5ee9916c22687b4abda5363ca6

2022-08-16 06:17 UTC, Leeosteves commented on src/screens/Favorites/styles.ts
> +  padding-bottom: 200px;
Resolved in commit 8be304bef5499c5ee9916c22687b4abda5363ca6

2022-08-16 06:17 UTC, Leeosteves commented on src/screens/Internal/index.tsx
> +              icon={ifExists(item) ? 'favorite' : 'like'}
Resolved in commit 8be304bef5499c5ee9916c22687b4abda5363ca6

2022-08-16 06:17 UTC, Leeosteves commented on src/screens/Internal/useInternalControler.tsx
> +export const useInternalControler = item => {
Resolved in commit 8be304bef5499c5ee9916c22687b4abda5363ca6

2022-09-02 04:24 UTC, IbraDajani approved these changes

2022-09-02 04:28 UTC, merged