Feat/pokemon search
IbraDajani/pokedex pull request #53
Opened 2022-08-15 08:24 UTC by Leeosteves

# 🚨 Fill in the fields below

[Filter Pokemons by name](https://trello.com/c/KWrPu4Kg/48-filter-pokemons-by-name)

## Description

```
~>Added search bar for pokemons by name.
```

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

- [ ] PRODUCT

  - [ ] Put PR link on ticket
  - [ ] Move the ticket

- [ ] DEVELOPERS

  - [ ] My code follows the style guidelines of this project
  - [ ] I have performed a self-review of my own code
  - [ ] I have commented my code, particularly in hard-to-understand areas
  - [ ] I have made corresponding changes to the documentation
  - [ ] My changes generate no new warnings and I added `TODO:`, `FIXME:`

- [ ] REVIEW
  - [ ] Add reviewers: The entire team and most influential people in the area/project
  - [ ] Assignees myself to it

🚨 - `Approve: Wait at least one influential in the project or more experienced`

# FRONTEND

## Screenshot or video of your application

🚨 - `Fill with your application

https://user-images.githubusercontent.com/106574167/184601597-5522ab22-3848-4917-a2c9-0eb6acefdbba.mp4

2022-08-15 23:40 UTC, IbraDajani requested changes

2022-08-15 23:40 UTC, IbraDajani commented on src/screens/Home/index.tsx
> +        placeholderTextColor="black"
placeholderColor should never be a strong color like black

it seems like the placeholder is the text itself

change it to something like a light grey

2022-08-15 23:40 UTC, IbraDajani commented on src/screens/Home/index.tsx
> +        color="black"
the color of the text and the placeholder with the same color is not a good idea

2022-08-15 23:40 UTC, IbraDajani commented on src/screens/Home/useHomeController.ts
> +  }, [textName]);
Daaaamm...

nice logic


just change the comments from Hooks to Effects

2022-08-16 06:28 UTC, Leeosteves commented on src/screens/Home/index.tsx
> +        placeholderTextColor="black"
resolved in commit d8afbe80ecd6ce00c4f340f562705183e99e0c85

2022-08-16 06:29 UTC, Leeosteves commented on src/screens/Home/index.tsx
> +        color="black"
resolved in commit d8afbe80ecd6ce00c4f340f562705183e99e0c85

2022-08-16 06:29 UTC, Leeosteves commented on src/screens/Home/useHomeController.ts
> +  }, [textName]);
resolved in commit d8afbe80ecd6ce00c4f340f562705183e99e0c85

2022-09-02 04:30 UTC, IbraDajani approved these changes

2022-09-02 04:43 UTC, merged